### ISSUE TITLE
Make abstract `SceneObject` + `Entity` class

### ISSUE THREAD

**Issue by cornelius-sevald** [cornelius-sevald/EvoBox#11]
The `SceneObject` class should be a super class for all objects in the scene, such as jumpmen.
It should expose some common behavior, such as a position and scale.

The `Entity` class should be a subclass of `SceneObject`, but should also have a visible component (for now).

Estimated time: 15 m.

**Comment by benshapiro69** [comment]
Fixed by b3badac.
